name = "exception"
version = "1.0.0"
gleam = ">= 0.32.0"
description = "A tiny package for dealing with exceptions"
licences = ["Apache-2.0"]

repository = { type = "github", user = "lpil", repo = "exception" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.30"

[dev-dependencies]
gleeunit = "~> 0.10"
simplifile = "~> 0.1"
